#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_credentials: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%', "*"]
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['Content-Type', 'Authorization']
#        expose_headers: ['Link']
#        max_age: 3600
#    paths:
#        '^/':
#            origin_regex: true
#            allow_origin: ['^http://localhost:[0-9]+', "*"]
#            allow_headers: ['X-Custom-Auth']
#            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
##            hosts: ['^api\.']
#nelmio_cors:
#    defaults:
#        origin_regex: false
#        allow_origin: ['http://localhost:5173'] # Remplacez par l'origine réelle de votre client
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['Content-Type', 'Authorization', 'X-Custom-Auth']
#        expose_headers: ['Link']
#        max_age:  3600
#        allow_credentials: true
#    paths:
#        '^/': ~

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age:  3600
        origin_regex: false
        hosts: []
    paths:
            '^/': ~